- name: variables and inventory
  hosts: localhost
  tasks:
    - name: print information
      ansible.builtin.debug:
        msg: "Hi, we are learning {{courses}} from Trainer {{Trainer}}, Duraction is {{Duraction}}."


