- name: datatypes
  hosts: localhost
  vars:
    Course: Devops with Aws # string
    Tools: #List
    - Linux
    - shell
    - Ansible
    Experiernce: # map or dictinory
      Devops: 3 # number
      Aws: 2
      Docker: 1
    Realproject: true # boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "course: {{Course}}, Tools coverd: {{Tools}}, Experirnce is:{{Experiernce}}, is realproject: {{Realproject:}}"
